const UNIDAD_EDIFICABILIDAD_NAME = Object.freeze({
  USAB0: 'U.S.A.B 0',
  USAB1: 'U.S.A.B 1',
  USAB2: 'U.S.A.B 2',
  USAM: 'U.S.A.M',
  USAA: 'U.S.A.A',
  CORREDOR_MEDIO: 'Corredor Medio',
  CORREDOR_ALTO: 'Corredor Alto'
})

const UNIDAD_EDIFICABILIDAD_CODE = Object.freeze({
  9: UNIDAD_EDIFICABILIDAD_NAME.USAB0,
  12: UNIDAD_EDIFICABILIDAD_NAME.USAB1,
  14.6: UNIDAD_EDIFICABILIDAD_NAME.USAB2,
  17.2: UNIDAD_EDIFICABILIDAD_NAME.USAM,
  22.8: UNIDAD_EDIFICABILIDAD_NAME.USAA,
  31.2: UNIDAD_EDIFICABILIDAD_NAME.CORREDOR_MEDIO,
  38: UNIDAD_EDIFICABILIDAD_NAME.CORREDOR_ALTO
})

const UNIDAD_EDIFICABILIDAD = Object.freeze({
  USAB0: 9,
  USAB1: 12,
  USAB2: 14.6,
  USAM: 17.2,
  USAA: 22.8,
  CORREDOR_MEDIO: 31.2,
  CORREDOR_ALTO: 38
})

export {
  UNIDAD_EDIFICABILIDAD_CODE,
  UNIDAD_EDIFICABILIDAD_NAME,
  UNIDAD_EDIFICABILIDAD
}
